core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    # Define image create url
    path('create/', views.image_create, name="create"),
    # Define image detail url
    path('detail/<int:pk>/<slug:slug>/', views.image_detail, name="detail"),
    # Define image like/dislike url
    path('like/', views.image_like, name="like"),
    # Define image list url
    path('', views.image_list, name='list'),
]

memories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include account urls
    path('account/', include('account.urls')),
    # Include social django urls
    path('social-auth/', include('social_django.urls', namespace='social')),
    # Include core urls
    path('core/', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    # Create image model and associate many-to-one relation with user model for user creates images
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="images_created", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to="images/%Y/%m/%d")
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # Associate many-to-many relation with user model for users like the images
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="images_liked", blank=True)
    # Add total likes field to denormalizing counts for image likes
    total_likes = models.PositiveIntegerField(default=0)
    class Meta:
        indexes = [models.Index(fields=["-created_at"]), models.Index(fields=["-total_likes"])]
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Override save method to automatically assign the slug name based on the title using slugify
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # Create canonical url for detail view
        return reverse("core:detail", args=[self.pk, self.slug])

core/forms.py
import requests
from django import forms
from django.utils.text import slugify
from django.core.files.base import ContentFile
from core.models import Image


class ImageCreateForm(forms.ModelForm):
    # Create a from for image creation which gets the url of the image to share with users
    class Meta:
        model = Image
        fields = ["title", "url", "description"]
        # URL field is hidden since the js will handel getting the image url from external resources
        widgets = {"url": forms.HiddenInput, }

    def clean_url(self):
        # Use clean_field_name to validate that the url is for an image when the is_valid method is called
        url = self.cleaned_data["url"]
        valid_extensions = ["jpg", "jpeg", "png"]
        # rsplit splits by the dot to a list and the extension is the second slice [1]
        extension = url.rsplit(".", 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("The fetched URL contains no valid image extension")
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        # Override form save method to download the image by its url
        image = super().save(commit=False)
        image_url = self.cleaned_data["url"]
        name = slugify(image.title)
        extension = image_url.rsplit(".", 1)[1].lower()
        image_name = f"{name}.{extension}"
        response = requests.get(image_url)
        # Get the image in media directory
        image.image.save(image_name, ContentFile(response.content), save=False)
        # Only save image when commit is true
        if commit:
            image.save()
        return image

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.http import require_POST
from core.forms import ImageCreateForm
from core.models import Image
from activity.utils import create_action
import redis
from django.conf import settings

# Setup redis connection to get images view count using redis
r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


@login_required
def image_create(request):
    # Create image using the bookmarklet
    if request.method == "POST":
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            new_image = form.save(commit=False)
            # Associate new image with authenticated user
            new_image.user = request.user
            new_image.save()
            # Record this activity stream using generic relationship of content type
            create_action(request.user, "bookmarked image", new_image)
            messages.success(request, "Image fetched successfully")
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
        template = "core/create.html"
        context = {"section": "images", "form": form}
        return render(request, template, context)


@login_required
def image_detail(request, slug, pk):
    # Create image detail view
    image = get_object_or_404(Image, slug=slug, pk=pk)
    # Increment the count of image detail view for each view
    total_views = r.incr(f'image:{image.id}:views')
    template = "core/detail.html"
    context = {"section": "images", "image": image, "total_views": total_views}
    return render(request, template, context)


@login_required
@require_POST
def image_like(request):
    # Create image like/dislike actions and set http method to post only
    image_id = request.POST.get("id")
    action = request.POST.get("action")
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == "like":
                image.users_like.add(request.user)
                # Record this activity stream using generic relationship of content type
                create_action(request.user, "likes", image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({"status": "ok"})
        except Image.DoesNotExist:
            pass
    return JsonResponse({"status": "error"})


@login_required
def image_list(request):
    # Create image list and paginate results
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get("page")
    images_only = request.GET.get("images_only")
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            # Stop ajax fetch api when list reaches the end
            return HttpResponse("")
        images = paginator.page(page.num_pages)
    if images_only:
        template = "core/list_images.html"
        context = {"section": "images", "images": images}
        return render(request, template, context)
    template = "core/list.html"
    context = {"section": "images", "images": images}
    return render(request, template, context)

core/templates/core/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

core/templates/core/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    <h2>{{ image.title }}</h2>
    {% load thumbnail %}
    <a href="{{ image.image.url }}">
        <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    </a>
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <div class="image-info">
            <div>
                <span class="count">
                    <span class="total">{{ total_likes }}</span>
                    {{ total_likes }} like{{ total_likes|pluralize }}
                </span>
                <span class="count">
                    {{ total_views }} view{{ total_views|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
                   class="like button">
                    {% if request.user not in users_like %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            {% for user in image.users_like.all %}
                <div>
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}">
                    {% endif %}
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}
{% block domready %}
    const url = '{% url "core:like" %}';
    var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
    }

    document.querySelector('a.like')
    .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;


    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;


    fetch(url, options)
    .then(response => response.json())
    .then(data => {
    if (data['status'] === 'ok')
    {
    var previousAction = likeButton.dataset.action;


    var action = previousAction === 'like' ? 'unlike' : 'like';
    likeButton.dataset.action = action;
    likeButton.innerHTML = action;


    var likeCount = document.querySelector('span.count .total');
    var totalLikes = parseInt(likeCount.innerHTML);
    likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
    }
    })
    });
{% endblock %}

core/templates/core/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
  <h1>Images bookmarked</h1>
  <div id="image-list">
    {% include "core/list_images.html" %}
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var emptyPage = false;
  var blockRequest = false;

  window.addEventListener('scroll', function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
      blockRequest = true;
      page += 1;

      fetch('?images_only=1&page=' + page)
      .then(response => response.text())
      .then(html => {
        if (html === '') {
          emptyPage = true;
        }
        else {
          var imageList = document.getElementById('image-list');
          imageList.insertAdjacentHTML('beforeEnd', html);
          blockRequest = false;
        }
      })
    }
  });

  const scrollEvent = new Event('scroll');
  window.dispatchEvent(scrollEvent);
{% endblock %}

core/templates/core/list_images.html
{% load thumbnail %}
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}